@startuml
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

title Class Diagram (CD) - UC027

class OpenClosePhasesJobOpeningUI <<interface>>

class OpenClosePhasesJobOpeningController <<controller>>

class JobOpeningManagementService <<service>>

class JobOpeningBuilder <<builder>>

class JobOpeningRepository <<repository>>

class RepositoryFactory <<factory>>

class JobOpening <<root>>

enum JobOpeningPhases <<value>>

OpenClosePhasesJobOpeningUI ..> OpenClosePhasesJobOpeningController

OpenClosePhasesJobOpeningController ..> JobOpeningManagementService : uses >
OpenClosePhasesJobOpeningController ..> JobOpeningRepository : accesses >

JobOpeningManagementService ..> JobOpeningBuilder : uses

JobOpeningRepository <.. RepositoryFactory : creates <
JobOpeningRepository ..> JobOpening : saves in database >

JobOpening --> JobOpeningPhases

@enduml