@startuml
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model (DM) - UC004

package SystemUserAggregate {
    class EmailAddress <<value>> <<id>>

    class SystemUser <<root>>

    class Name <<value>>

    class RoleSet <<value>>

    class RoleAssignment <<entity>>

    class Role <<value>>

    class RoleSet <<value>>

    class Set<RoleAssignment> <<value>>
}

SystemUser --> Name
SystemUser --> EmailAddress
SystemUser --left-> RoleSet
RoleSet ..|> Set
RoleSet .down.> RoleAssignment
Role <-down- RoleAssignment

@enduml