@startuml

title System Sequence Diagram - UC008
actor Operator as Operator
participant ":System" as System

activate Operator

    Operator -> System: List all candidates
    activate System

    System -> System: Retrieve all candidates
    activate System

    System --> System
    deactivate System

    System -> Operator: Display all candidates
    deactivate Operator


@enduml