@startuml
'https://plantuml.com/class-diagram

skinparam packageStyle rectangle
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam linetype ortho

top to bottom direction
left to right direction

hide methods
hide circle

title Domain Model - UC032

package SystemUserAggregate {
    class SystemUser <<Root Entity>>
    class Username <<Value Object>>
    enum Role <<Value Object>> {
        ADMIN
        CUSTOMER_MANAGER
        OPERATOR
        CUSTOMER
        CANDIDATE
    }
}
note right of SystemUserAggregate: out of scope (provided by EAPLI FRAMEWORK)

class CustomerManager
note left of CustomerManager: conceptual class

package CustomerAggregate {
    class Customer <<Root Entity>>
    class CustomerCode <<Value Object>>
}

package CandidateAggregate {
    class Candidate <<Root Entity>>
}

package JobOpeningAggregate {
    class JobOpening <<Root Entity>>
    class JobReference <<Value Object>>
    enum Phase <<Value Object>> {
        APPLICATION
        SCREENING
        INTERVIEWS
        ANALYSIS
        RESULT
    }
    class PhaseDetails <<Value Object>>
    class DateInterval <<Value Object>>
    enum Status <<Value Object>> {
        PENDING
        IN_PROGRESS
        COMPLETED
    }
    package InterviewModelPackage {
        class InterviewModel <<Value Object>>
        class InterviewModelDesignation <<Value Object>>
        class InterviewModelDescription <<Value Object>>
        class InterviewModelFileExtension <<Value Object>>
        class InterviewModelFQCLassName <<Value Object>>
    }
}
note right of InterviewModelDesignation: Designation (provided by EAPLI FRAMEWORK)
note right of InterviewModelDescription: Description (provided by EAPLI FRAMEWORK)
note right of InterviewModelFileExtension: FileExtension (provided by EAPLI FRAMEWORK)
note right of InterviewModelFQCLassName: FQClassName (provided by EAPLI FRAMEWORK)

package JobApplicationAggregate {
    class JobApplication <<Root Entity>>
    class JobApplicationReference <<Value Object>>
    package InterviewPackage {
        class Interview <<Value Object>>
        class InterviewDate <<Value Object>>
        class InterviewName <<Value Object>>
        class InterviewDescription <<Value Object>>
        class InterviewGrade <<Value Object>>
    }
}
note right of InterviewName: Designation (provided by EAPLI FRAMEWORK)
note right of InterviewDescription: Description (provided by EAPLI FRAMEWORK)

SystemUser "1" -- "1" Username
SystemUser "1" -- "*" Role
note right of Username: in the context of our app, is the EmailAddress of the user

SystemUser <--- CustomerManager : is a <
SystemUser <--- Customer : is a <
SystemUser <--- Candidate : is a <


CustomerManager "1" -------- "*" Customer : manages >

Candidate "1" ------- "*" JobApplication : applies to >

CustomerManager "1" -- "*" JobOpening : creates >

JobOpening "1" ------- "*" JobApplication : to <
JobOpening "1" --------- "0..1" InterviewModel : has >
JobOpening "1" -- "1" JobReference : identified by >
JobOpening "1" -- "4..5" Phase : has >

Phase "1" -- "1" PhaseDetails : with >
PhaseDetails "1" -- "1" Status : has >
PhaseDetails "1" -- "1" DateInterval : has >

JobApplication "1" -- "1" JobApplicationReference : identified by >
JobApplication "1" ---- "0..1" Interview : has >

Interview "1" -- "1" InterviewDate : on >
Interview "1" -- "1" InterviewName : identified by >
Interview "1" -- "1" InterviewDescription : with >
Interview "1" -- "1" InterviewGrade : with >

InterviewModel "1" -- "1" InterviewModelDesignation : identified by >
InterviewModel "1" -- "1" InterviewModelDescription : with >
InterviewModel "1" -- "1" InterviewModelFileExtension : with >
InterviewModel "1" -- "1" InterviewModelFQCLassName : with >

@enduml