@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - UC025
actor Operator as Actor
participant ":System" as System

activate Actor
    Actor -> System: Login
    activate System

        System -> System: Validate login

        System --> Actor: Allow access to the backoffice application with operator permissions
    deactivate System

    Actor -> System: Select the option to disable a candidate
    activate System

        System --> Actor: Show all active candidates and ask to select the candidate to be disabled
    deactivate System

    Actor -> System: Select candidate to be disabled
    activate System

        System -> System: Disable the selected candidate

        System --> Actor: Inform that the candidate was disabled and deny the selected candidate access to the Candidate App
    deactivate System
deactivate Actor

@enduml