@startuml
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

title Class Diagram (CD) - UC014

class ListUsersUI <<interface>>

class ListUsersController <<controller>>

class UserRepository <<repository>>

class UserManagementService <<service>>

class EmailAddress <<value>> <<id>>

class SystemUser <<root>>

class Candidate <<root>>

class Password <<value>>

class Name <<value>>

class PasswordPolicy <<service>>

class PasswordEncoder <<service>>

class RoleSet <<value>>

class RoleAssignment <<entity>>

enum Role <<value>>

class RoleSet <<value>>

class Set<RoleAssignment> <<value>>

ListUsersUI ..> ListUsersController

ListUsersController ..> UserRepository : accesses >

UserRepository ..> SystemUser : saves in database >
ListUsersController ..> UserManagementService : uses >

SystemUser ..> Name
SystemUser ..> Password
SystemUser ..> EmailAddress

SystemUser -left-> RoleSet
RoleSet ..|> Set
RoleSet .down.> RoleAssignment
Role <-down- RoleAssignment

SystemUser -right.> Candidate : has >

Password ..> PasswordPolicy
Password ..> PasswordEncoder : creates <

@enduml