@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - UC032
actor "Customer Manager" as CM
participant ":System" as System

autonumber 1

activate CM
CM -> System: Requests to evaluate a job opening's interviews
        activate System
    System -> System: Retrieve job opening's list
        activate System
    deactivate System
    System -> System: Select job opening's with phase's interview completed
        activate System
    deactivate System
    System --> CM: Display job opening's list
deactivate System
CM -> System: Select one job opening to rank interviews
    activate System
    System -> System: Retrieve job opening's job applications
        activate System
    deactivate System
    loop for each job application
            System -> System: Retrieve job application's interviews
            activate System
        deactivate System
            System -> System: Retrieve interview's grade
            activate System
        deactivate System
    end loop
    System --> CM: Display interview's grades
    System --> CM: Save interview's grades?
    deactivate System
    alt confirm
    CM -> System: Confirms to save interview's grades
        activate System
    System -> System: Save interview's grades
        activate System
    deactivate System
    else cancel
    CM -> System: Cancels to save interview's grades
    end alt
    System --> CM: Shows (un)successful message
    deactivate System
deactivate CM

@enduml