@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - UC027
actor CustomerManager as CM
participant ":System" as System

activate CM

        CM -> System: Login
    activate System

        System -> System: Validate login

        System --> CM: Allow access to the backoffice \napplication with Customer Manager permissions
    deactivate System

        CM -> System: Select the option to close the job opening
    activate System

        System --> CM: Display job opening that has phases
    deactivate System


        CM -> System: Select the job opening to be closed

    activate System

        System -> CM: Display job opening phases

        loop for each phase
            CM -> System: Select the phase to be closed

            System -> System: Validate the phase to be closed

            System --> CM: Allow the phase to be closed

    deactivate System

        end loop

        CM -> System: Confirm the job opening to be closed
    activate System

        alt Phases is enabled
            System --> CM: Phases of the process for a job opening enabled successfully
        else Phases is not enabled
            System --> CM: Phases of the process for a job opening not enabled successfully
        end

    alt if allPhases = Status.COMPLETED

        System --> CM: Job opening completed successfully

    end

    deactivate System

deactivate CM

@enduml