@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title system Sequence Diagram (SSD) - UC039
actor "Customer Manager" as actor
participant ":System" as system

activate actor

    actor -> system: Login
    activate system

    system -> actor: (un)success of the operation
    deactivate system

deactivate actor

@enduml