@startuml
skinparam packageStyle rectangle
skinparam shadowing false

skinparam classAttributeIconSize 0

top to bottom direction
left to right direction

hide circle
hide methods

title Domain Model (DM) - UC027

package SystemUserAggregate {
    class SystemUser <<Root Entity>>
    class Name <<Value Object>>
    class Email <<Value Object>>
    class Password <<Value Object>>
    enum Role <<Value Object>> {
        ADMIN
        CUSTOMER_MANAGER
        OPERATOR
        CUSTOMER
    }
}

package CustomerManagerAggregate {
    class CustomerManager <<Root Entity>>
}
note right of CustomerManager: conceptual class

package JobOpeningAggregate{
    class JobOpening <<Root Entity>>
    class JobOpeningProcess <<Value Object>>
    enum Phase <<Value Object>> {
        APPLICATION
        SCREENING
        INTERVIEWS
        ANALYSIS
        RESULT
    }
    enum PhasesStatus <<Value Object>> {
        PENDING
        OPEN
        CLOSE
    }
}

CustomerManager "1" -- "*" JobOpening



SystemUser "1" -- "1" Name
SystemUser "1" -- "1" Email
SystemUser "1" -- "1" Password
SystemUser "1" -- "*" Role

SystemUser <--- CustomerManager

JobOpening "1" -- "1" JobOpeningProcess
JobOpeningProcess -- PhasesStatus
JobOpeningProcess -- Phase

@enduml